spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:blogdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop # 애플리케이션 실행 시 스키마 생성, 종료 시 삭제
    show-sql: true
    properties:
      hibernate:
        format_sql: true